# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Virtual Newcomer Packet
email: adambaileyland@gmail.com
description: A virtual newcomer packet.
# baseurl: /virtual-newcomer-packet
# baseurl: /
baseurl: "" # toggle local build
url: "" # the base hostname & protocol for your site

# Logo settings
logo-image-url: images/logo.svg
font-awesome-icon-logo:

# Social settings
github_username: adambaileyland

# Build settings
markdown: kramdown

# Layout settings
home-link-in-menu: yes

# Plugins
plugins:
  - jekyll-multiple-languages-plugin

#Leave English in base root
default_locale_in_subfolder: true

# Languages
languages: ["es"]

#Leave English in base root
default_locale_in_subfolder: true

# Exclude this stuff from other languages
exclude_from_localizations: ["javascript", "css", "scripts"]